# Generated by Django 5.2.9 on 2025-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
        migrations.AddField(
            model_name='job',
            name='chapters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
